"""
SHL Individual Test Solutions catalog.
Each entry: name, url, test_types (list of key letters), type_labels, duration, languages,
job_families, job_levels, description (for semantic search).
"""

CATALOG = [
    # ── Ability & Aptitude ──────────────────────────────────────────────
    {
        "name": "SHL Verify Interactive G+",
        "url": "https://www.shl.com/products/product-catalog/view/shl-verify-interactive-g/",
        "test_types": ["A"],
        "type_labels": ["Ability & Aptitude"],
        "duration": "36 minutes",
        "languages": "English (USA), Chinese Traditional, Korean, Serbian (+29 more)",
        "job_families": ["all"],
        "job_levels": ["Graduate", "Professional", "Manager", "Director", "Executive", "Senior"],
        "description": "Adaptive general cognitive ability test covering inductive, numerical, and deductive reasoning. Suitable for senior professional and graduate roles requiring learning agility.",
    },
    {
        "name": "SHL Verify Interactive – Numerical Reasoning",
        "url": "https://www.shl.com/products/product-catalog/view/shl-verify-interactive-numerical-reasoning/",
        "test_types": ["A", "S"],
        "type_labels": ["Ability & Aptitude", "Simulations"],
        "duration": "20 minutes",
        "languages": "French, German, Italian, Dutch (+30 more)",
        "job_families": ["Finance", "Business", "Analytics"],
        "job_levels": ["Graduate", "Professional", "Manager"],
        "description": "Numerical reasoning test measuring ability to interpret data, tables, graphs and financial figures. Ideal for finance, analyst, and business roles.",
    },
    {
        "name": "SHL Verify Interactive – Verbal Reasoning",
        "url": "https://www.shl.com/products/product-catalog/view/shl-verify-interactive-verbal-reasoning/",
        "test_types": ["A"],
        "type_labels": ["Ability & Aptitude"],
        "duration": "17 minutes",
        "languages": "English (USA), French, German, Dutch (+15 more)",
        "job_families": ["all"],
        "job_levels": ["Graduate", "Professional", "Manager"],
        "description": "Verbal reasoning test assessing the ability to evaluate written information and draw logical conclusions. Suits roles requiring communication and analytical thinking.",
    },
    {
        "name": "SHL Verify Interactive – Inductive Reasoning",
        "url": "https://www.shl.com/products/product-catalog/view/shl-verify-interactive-inductive-reasoning/",
        "test_types": ["A"],
        "type_labels": ["Ability & Aptitude"],
        "duration": "24 minutes",
        "languages": "English (USA), German, French (+20 more)",
        "job_families": ["Technology", "Engineering", "all"],
        "job_levels": ["Graduate", "Professional", "Manager"],
        "description": "Inductive/abstract reasoning measuring ability to identify patterns and rules. Suits technical and innovation-focused roles.",
    },
    {
        "name": "SHL Verify Interactive – Deductive Reasoning",
        "url": "https://www.shl.com/products/product-catalog/view/shl-verify-interactive-deductive-reasoning/",
        "test_types": ["A"],
        "type_labels": ["Ability & Aptitude"],
        "duration": "20 minutes",
        "languages": "English (USA), German, French (+15 more)",
        "job_families": ["all"],
        "job_levels": ["Graduate", "Professional", "Manager"],
        "description": "Deductive reasoning assessment measuring logical thinking and conclusions from given premises.",
    },
    # ── Personality & Behavior ──────────────────────────────────────────
    {
        "name": "Occupational Personality Questionnaire OPQ32r",
        "url": "https://www.shl.com/products/product-catalog/view/occupational-personality-questionnaire-opq32r/",
        "test_types": ["P"],
        "type_labels": ["Personality & Behavior"],
        "duration": "25 minutes",
        "languages": "English International, French (Canada), Portuguese, Chinese Simplified (+35 more)",
        "job_families": ["all"],
        "job_levels": ["Graduate", "Professional", "Manager", "Director", "Executive", "Senior"],
        "description": "Gold-standard personality questionnaire measuring 32 behavioural dimensions including relationships with people, thinking style, and feelings/emotions. Used for selection and development across all levels.",
    },
    {
        "name": "Dependability and Safety Instrument (DSI)",
        "url": "https://www.shl.com/products/product-catalog/view/dependability-and-safety-instrument-dsi/",
        "test_types": ["P"],
        "type_labels": ["Personality & Behavior"],
        "duration": "10 minutes",
        "languages": "Portuguese (Brazil), Chinese Traditional, Danish, Dutch (+13 more)",
        "job_families": ["Manufacturing", "Healthcare", "Logistics", "Frontline"],
        "job_levels": ["Entry", "Frontline", "Professional"],
        "description": "Measures integrity, reliability, safety attitudes, and dependability. Predicts safe and compliant behaviour in safety-critical, frontline, and trust-sensitive roles.",
    },
    {
        "name": "Manufac. & Indust. - Safety & Dependability 8.0",
        "url": "https://www.shl.com/products/product-catalog/view/safety-and-dependability-focus-8-0/",
        "test_types": ["P"],
        "type_labels": ["Personality & Behavior"],
        "duration": "16 minutes",
        "languages": "English (USA), German, Latin American Spanish, French (+4 more)",
        "job_families": ["Manufacturing", "Industrial", "Logistics"],
        "job_levels": ["Entry", "Frontline", "Professional"],
        "description": "Sector-specific personality bundle with industrial norms calibrated for manufacturing and industrial workforces. Focuses on safety compliance and dependability.",
    },
    {
        "name": "OPQ Universal Competency Report 2.0",
        "url": "https://www.shl.com/products/product-catalog/view/opq-universal-competency-report-2-0/",
        "test_types": ["P"],
        "type_labels": ["Personality & Behavior"],
        "duration": "—",
        "languages": "—",
        "job_families": ["all"],
        "job_levels": ["Professional", "Manager", "Director", "Executive"],
        "description": "OPQ32r report presenting personality results against the Universal Competency Framework for selection and benchmarking decisions.",
    },
    {
        "name": "OPQ Leadership Report",
        "url": "https://www.shl.com/products/product-catalog/view/opq-leadership-report/",
        "test_types": ["P"],
        "type_labels": ["Personality & Behavior"],
        "duration": "—",
        "languages": "Dutch, English International, English (USA), Romanian (+10 more)",
        "job_families": ["Leadership", "Management"],
        "job_levels": ["Manager", "Director", "Executive"],
        "description": "OPQ32r output formatted for senior leadership selection, benchmarking against leadership competencies and executive norms.",
    },
    {
        "name": "OPQ MQ Sales Report",
        "url": "https://www.shl.com/products/product-catalog/view/opq-mq-sales-report/",
        "test_types": ["P"],
        "type_labels": ["Personality & Behavior"],
        "duration": "—",
        "languages": "Portuguese (Brazil), Spanish, Danish, Dutch, Finnish (+24 more)",
        "job_families": ["Sales"],
        "job_levels": ["Professional", "Manager"],
        "description": "Sales-specific report from OPQ32r, optionally enriched with Motivation Questionnaire (MQ) data for sales drives and motivators.",
    },
    {
        "name": "Sales Transformation 2.0 - Individual Contributor",
        "url": "https://www.shl.com/products/product-catalog/view/salestransformationreport2-0-individualcontributor/",
        "test_types": ["P"],
        "type_labels": ["Personality & Behavior"],
        "duration": "—",
        "languages": "—",
        "job_families": ["Sales"],
        "job_levels": ["Professional"],
        "description": "Assesses sales rep readiness for digital-first selling transformation. Focuses on how individual contributors show up in a modern sales environment.",
    },
    {
        "name": "Entry Level Customer Serv - Retail & Contact Center",
        "url": "https://www.shl.com/products/product-catalog/view/entry-level-customer-serv-retail-and-contact-center/",
        "test_types": ["P", "C"],
        "type_labels": ["Personality & Behavior", "Competencies"],
        "duration": "19 minutes",
        "languages": "Latin American Spanish, German, French, Chinese Simplified (+10 more)",
        "job_families": ["Customer Service", "Contact Center", "Retail"],
        "job_levels": ["Entry"],
        "description": "Personality and competency screen for entry-level customer service, retail, and contact center roles. Measures service orientation, reliability, and customer focus.",
    },
    # ── Biodata & Situational Judgment ─────────────────────────────────
    {
        "name": "Graduate Scenarios",
        "url": "https://www.shl.com/products/product-catalog/view/graduate-scenarios/",
        "test_types": ["B"],
        "type_labels": ["Biodata & Situational Judgment"],
        "duration": "Untimed",
        "languages": "English International",
        "job_families": ["all"],
        "job_levels": ["Graduate"],
        "description": "Situational judgement test designed for graduate candidates. Presents work-context scenarios to assess decision-making in professional settings.",
    },
    {
        "name": "Customer Service Phone Simulation",
        "url": "https://www.shl.com/products/product-catalog/view/customer-service-phone-simulation/",
        "test_types": ["B", "S"],
        "type_labels": ["Biodata & Situational Judgment", "Simulations"],
        "duration": "20 minutes",
        "languages": "French (Canada), Portuguese (Brazil), Dutch, Italian (+7 more)",
        "job_families": ["Customer Service", "Contact Center"],
        "job_levels": ["Entry", "Professional"],
        "description": "Bundled older solution combining personality, biodata, and simulation for customer service phone roles. Used for finalist-stage depth assessment.",
    },
    # ── Knowledge & Skills ──────────────────────────────────────────────
    {
        "name": "Financial Accounting (New)",
        "url": "https://www.shl.com/products/product-catalog/view/financial-accounting-new/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "9 minutes",
        "languages": "English (USA)",
        "job_families": ["Finance", "Accounting"],
        "job_levels": ["Graduate", "Professional"],
        "description": "Tests financial accounting knowledge including journal entries, financial statements, and accounting principles.",
    },
    {
        "name": "Basic Statistics (New)",
        "url": "https://www.shl.com/products/product-catalog/view/basic-statistics-new/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "10 minutes",
        "languages": "English (USA)",
        "job_families": ["Finance", "Analytics", "Research"],
        "job_levels": ["Graduate", "Professional"],
        "description": "Tests foundational statistics knowledge: mean, median, distributions, probability, and data interpretation.",
    },
    {
        "name": "HIPAA (Security)",
        "url": "https://www.shl.com/products/product-catalog/view/hipaa-security/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "15 minutes",
        "languages": "English (USA)",
        "job_families": ["Healthcare"],
        "job_levels": ["Entry", "Professional"],
        "description": "Assesses knowledge of HIPAA security provisions and patient data protection requirements in healthcare settings.",
    },
    {
        "name": "Medical Terminology (New)",
        "url": "https://www.shl.com/products/product-catalog/view/medical-terminology-new/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "3 minutes",
        "languages": "English (USA)",
        "job_families": ["Healthcare"],
        "job_levels": ["Entry", "Professional"],
        "description": "Brief knowledge check on common medical terms for healthcare administrative and clinical support roles.",
    },
    {
        "name": "Workplace Health and Safety (New)",
        "url": "https://www.shl.com/products/product-catalog/view/workplace-health-and-safety-new/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "9 minutes",
        "languages": "English (USA)",
        "job_families": ["Manufacturing", "Industrial", "Logistics", "Frontline"],
        "job_levels": ["Entry", "Frontline", "Professional"],
        "description": "Tests knowledge of workplace health and safety regulations, hazard identification, and safety procedures.",
    },
    {
        "name": "MS Excel (New)",
        "url": "https://www.shl.com/products/product-catalog/view/ms-excel-new/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "6 minutes",
        "languages": "English (USA), Spanish, French, Portuguese (Brazil)",
        "job_families": ["Administration", "Finance", "all"],
        "job_levels": ["Entry", "Professional"],
        "description": "Quick knowledge-only test for Microsoft Excel covering formulas, functions, and spreadsheet concepts.",
    },
    {
        "name": "MS Word (New)",
        "url": "https://www.shl.com/products/product-catalog/view/ms-word-new/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "4 minutes",
        "languages": "Spanish, French, Portuguese (Brazil), English (USA)",
        "job_families": ["Administration", "all"],
        "job_levels": ["Entry", "Professional"],
        "description": "Quick knowledge-only test for Microsoft Word covering formatting, document creation, and editing concepts.",
    },
    {
        "name": "Microsoft Excel 365 (New)",
        "url": "https://www.shl.com/products/product-catalog/view/microsoft-excel-365-new/",
        "test_types": ["K", "S"],
        "type_labels": ["Knowledge & Skills", "Simulations"],
        "duration": "35 minutes",
        "languages": "English (USA)",
        "job_families": ["Administration", "Finance", "all"],
        "job_levels": ["Entry", "Professional"],
        "description": "Comprehensive Excel 365 simulation plus knowledge test assessing real-world spreadsheet skills through hands-on tasks.",
    },
    {
        "name": "Microsoft Word 365 (New)",
        "url": "https://www.shl.com/products/product-catalog/view/microsoft-word-365-new/",
        "test_types": ["K", "S"],
        "type_labels": ["Knowledge & Skills", "Simulations"],
        "duration": "35 minutes",
        "languages": "English (USA)",
        "job_families": ["Administration", "all"],
        "job_levels": ["Entry", "Professional"],
        "description": "Comprehensive Word 365 simulation plus knowledge test evaluating document creation and formatting through hands-on tasks.",
    },
    {
        "name": "Microsoft Word 365 - Essentials (New)",
        "url": "https://www.shl.com/products/product-catalog/view/microsoft-word-365-essentials-new/",
        "test_types": ["K", "S"],
        "type_labels": ["Knowledge & Skills", "Simulations"],
        "duration": "25 minutes",
        "languages": "English (USA)",
        "job_families": ["Administration", "Healthcare", "all"],
        "job_levels": ["Entry", "Professional"],
        "description": "Essentials-level Word 365 simulation and knowledge test for roles that use Word as a secondary tool.",
    },
    {
        "name": "Core Java (Advanced Level) (New)",
        "url": "https://www.shl.com/products/product-catalog/view/core-java-advanced-level-new/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "13 minutes",
        "languages": "English (USA)",
        "job_families": ["Technology", "Software Engineering"],
        "job_levels": ["Senior", "Professional"],
        "description": "Advanced Java knowledge test covering concurrency, JVM internals, performance tuning, and design patterns for senior engineers.",
    },
    {
        "name": "Core Java (Entry Level) (New)",
        "url": "https://www.shl.com/products/product-catalog/view/core-java-entry-level-new/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "9 minutes",
        "languages": "English (USA)",
        "job_families": ["Technology", "Software Engineering"],
        "job_levels": ["Graduate", "Entry"],
        "description": "Entry-level Java knowledge test for reading and modifying existing code, suitable for graduate software engineering hires.",
    },
    {
        "name": "Spring (New)",
        "url": "https://www.shl.com/products/product-catalog/view/spring-new/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "9 minutes",
        "languages": "English (USA)",
        "job_families": ["Technology", "Software Engineering"],
        "job_levels": ["Professional", "Senior"],
        "description": "Tests Spring Framework knowledge for Java backend development, dependency injection, Spring Boot, and REST APIs.",
    },
    {
        "name": "RESTful Web Services (New)",
        "url": "https://www.shl.com/products/product-catalog/view/restful-web-services-new/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "12 minutes",
        "languages": "English (USA)",
        "job_families": ["Technology", "Software Engineering"],
        "job_levels": ["Professional", "Senior"],
        "description": "Assesses knowledge of REST API design principles, HTTP methods, status codes, and web services integration.",
    },
    {
        "name": "SQL (New)",
        "url": "https://www.shl.com/products/product-catalog/view/sql-new/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "9 minutes",
        "languages": "English (USA)",
        "job_families": ["Technology", "Data", "Finance"],
        "job_levels": ["Graduate", "Professional", "Senior"],
        "description": "SQL knowledge test covering queries, joins, aggregations, and relational database concepts.",
    },
    {
        "name": "Amazon Web Services (AWS) Development (New)",
        "url": "https://www.shl.com/products/product-catalog/view/amazon-web-services-aws-development-new/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "6 minutes",
        "languages": "English (USA)",
        "job_families": ["Technology", "Cloud", "DevOps"],
        "job_levels": ["Professional", "Senior"],
        "description": "Tests AWS cloud services knowledge including EC2, S3, Lambda, and deployment patterns.",
    },
    {
        "name": "Docker (New)",
        "url": "https://www.shl.com/products/product-catalog/view/docker-new/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "10 minutes",
        "languages": "English (USA)",
        "job_families": ["Technology", "DevOps", "Cloud"],
        "job_levels": ["Professional", "Senior"],
        "description": "Assesses Docker containerisation knowledge: images, containers, Dockerfile, and orchestration basics.",
    },
    {
        "name": "Linux Programming (General)",
        "url": "https://www.shl.com/products/product-catalog/view/linux-programming-general/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "25 minutes",
        "languages": "English (USA)",
        "job_families": ["Technology", "Systems", "DevOps"],
        "job_levels": ["Professional", "Senior"],
        "description": "Tests Linux systems programming knowledge including shell scripting, system calls, process management, and kernel concepts.",
    },
    {
        "name": "Networking and Implementation (New)",
        "url": "https://www.shl.com/products/product-catalog/view/networking-and-implementation-new/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "7 minutes",
        "languages": "English (USA)",
        "job_families": ["Technology", "Infrastructure", "Networking"],
        "job_levels": ["Professional", "Senior"],
        "description": "Tests networking fundamentals: TCP/IP, DNS, routing, protocols, and infrastructure implementation.",
    },
    {
        "name": "SVAR Spoken English (US) (New)",
        "url": "https://www.shl.com/products/product-catalog/view/svar-spoken-english-us-new/",
        "test_types": ["K"],
        "type_labels": ["Simulations"],
        "duration": "—",
        "languages": "English (USA)",
        "job_families": ["Customer Service", "Contact Center"],
        "job_levels": ["Entry"],
        "description": "Automated spoken English screen calibrated for US accent. Used for high-volume contact centre and customer service hiring.",
    },
    {
        "name": "SVAR Spoken English (UK) (New)",
        "url": "https://www.shl.com/products/product-catalog/view/svar-spoken-english-uk-new/",
        "test_types": ["K"],
        "type_labels": ["Simulations"],
        "duration": "—",
        "languages": "English (UK)",
        "job_families": ["Customer Service", "Contact Center"],
        "job_levels": ["Entry"],
        "description": "Automated spoken English screen calibrated for UK accent.",
    },
    {
        "name": "SVAR Spoken English (Australia) (New)",
        "url": "https://www.shl.com/products/product-catalog/view/svar-spoken-english-australia-new/",
        "test_types": ["K"],
        "type_labels": ["Simulations"],
        "duration": "—",
        "languages": "English (Australia)",
        "job_families": ["Customer Service", "Contact Center"],
        "job_levels": ["Entry"],
        "description": "Automated spoken English screen calibrated for Australian accent.",
    },
    {
        "name": "SVAR Spoken English (India) (New)",
        "url": "https://www.shl.com/products/product-catalog/view/svar-spoken-english-india-new/",
        "test_types": ["K"],
        "type_labels": ["Simulations"],
        "duration": "—",
        "languages": "English (India)",
        "job_families": ["Customer Service", "Contact Center"],
        "job_levels": ["Entry"],
        "description": "Automated spoken English screen calibrated for Indian accent.",
    },
    # ── Simulations ─────────────────────────────────────────────────────
    {
        "name": "Contact Center Call Simulation (New)",
        "url": "https://www.shl.com/products/product-catalog/view/contact-center-call-simulation-new/",
        "test_types": ["S"],
        "type_labels": ["Simulations"],
        "duration": "15 minutes",
        "languages": "English (USA)",
        "job_families": ["Customer Service", "Contact Center"],
        "job_levels": ["Entry"],
        "description": "Standalone in-call interaction simulation for contact centre roles. Tests how candidates handle customer calls in a realistic scenario.",
    },
    {
        "name": "Smart Interview Live Coding",
        "url": "https://www.shl.com/products/product-catalog/view/smart-interview-live-coding/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "Variable",
        "languages": "English (USA)",
        "job_families": ["Technology", "Software Engineering"],
        "job_levels": ["Professional", "Senior"],
        "description": "Adaptive live coding interview enabling panellists to assess programming skills through interactive tasks in any language or framework.",
    },
    # ── Competencies / Development ───────────────────────────────────────
    {
        "name": "Global Skills Assessment",
        "url": "https://www.shl.com/products/product-catalog/view/global-skills-assessment/",
        "test_types": ["C", "K"],
        "type_labels": ["Competencies", "Knowledge & Skills"],
        "duration": "16 minutes",
        "languages": "Indonesian, Italian, Swedish, Thai, Portuguese (Brazil) (+19 more)",
        "job_families": ["all"],
        "job_levels": ["Professional", "Manager"],
        "description": "Self-reported competency and skills audit assessing current skill levels across functional and behavioural areas. Used for talent audits and re-skilling initiatives.",
    },
    {
        "name": "Global Skills Development Report",
        "url": "https://www.shl.com/products/product-catalog/view/global-skills-development-report/",
        "test_types": ["D"],
        "type_labels": ["Development & 360"],
        "duration": "—",
        "languages": "—",
        "job_families": ["all"],
        "job_levels": ["Professional", "Manager"],
        "description": "Development report generated from Global Skills Assessment data, producing targeted re-skilling and development recommendations.",
    },
    # ── Additional common assessments ────────────────────────────────────
    {
        "name": "Accounts Payable (New)",
        "url": "https://www.shl.com/products/product-catalog/view/accounts-payable-new/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "10 minutes",
        "languages": "English (USA)",
        "job_families": ["Finance", "Accounting"],
        "job_levels": ["Entry", "Professional"],
        "description": "Tests accounts payable knowledge: invoice processing, payment cycles, reconciliation, and vendor management.",
    },
    {
        "name": "Accounts Payable Simulation (New)",
        "url": "https://www.shl.com/products/product-catalog/view/accounts-payable-simulation-new/",
        "test_types": ["S"],
        "type_labels": ["Simulations"],
        "duration": "20 minutes",
        "languages": "English (USA)",
        "job_families": ["Finance", "Accounting"],
        "job_levels": ["Entry", "Professional"],
        "description": "Simulation-based assessment of real accounts payable tasks: processing invoices and handling payment workflows.",
    },
    {
        "name": "Python (New)",
        "url": "https://www.shl.com/products/product-catalog/view/python-new/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "10 minutes",
        "languages": "English (USA)",
        "job_families": ["Technology", "Data", "Software Engineering"],
        "job_levels": ["Graduate", "Professional", "Senior"],
        "description": "Python programming knowledge test covering syntax, data structures, OOP, and standard library usage.",
    },
    {
        "name": "Angular (New)",
        "url": "https://www.shl.com/products/product-catalog/view/angular-new/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "10 minutes",
        "languages": "English (USA)",
        "job_families": ["Technology", "Frontend", "Software Engineering"],
        "job_levels": ["Professional", "Senior"],
        "description": "Tests Angular framework knowledge: components, services, routing, and TypeScript integration.",
    },
    {
        "name": "JavaScript (New)",
        "url": "https://www.shl.com/products/product-catalog/view/javascript-new/",
        "test_types": ["K"],
        "type_labels": ["Knowledge & Skills"],
        "duration": "10 minutes",
        "languages": "English (USA)",
        "job_families": ["Technology", "Frontend", "Software Engineering"],
        "job_levels": ["Graduate", "Professional", "Senior"],
        "description": "JavaScript knowledge test covering DOM, async, ES6+, and browser APIs.",
    },
]
